trigger:
  branches:
    include:
      - develop

pr:
  branches:
    include:
      - develop

pool:
  name: 'linux_onpremises'

variables:
  system.debug: true

steps:
- task: Cache@2
  displayName: Azure caching
  inputs:
    key: 'cache | "$(Agent.OS)" | $(Build.SourceVersion)'
    path: $(Build.SourcesDirectory)/pipeline_cache/
    restoreKeys: | 
      cache | "$(Agent.OS)"

- script: |
    cat $(Build.SourcesDirectory)/pipeline_cache/azure_cache.txt
  displayName: Display contents of azure_cache.txt
  
- script: |
    current_datetime=$(date +"%Y-%m-%d %H:%M:%S")
    echo "Cache Metadata:" > $(Build.SourcesDirectory)/pipeline_cache/azure_cache.txt
    echo "This is the cache of branch $(Build.SourceBranch), build $(Build.BuildNumber) at time $current_datetime." >> $(Build.SourcesDirectory)/pipeline_cache/azure_cache.txt
  displayName: Write cache metadata
